name: RUN ENV
on:
  workflow_dispatch:
    inputs:
      target_environment:
        description: 'Target environment'
        required: true
        type: string
        default: 'staging'
jobs:
  TRYING_TO_RUN_ANOTHER_WORKFLOW:
    runs-on: ubuntu-latest
    steps:
        - uses: Nico-s-Random-Organization/test-node-cli-app/github/workflows/post-merge
          with:
            target_environment : ${{ github.event.inputs.target_environment }}