name: RUN ENV
on:
  push:
jobs:
  TRYING_TO_RUN_ANOTHER_WORKFLOW:
    runs-on: ubuntu-latest
    steps:
        - name: checkout
          uses: actions/checkout@v3
        - name: setup node
          uses: actions/setup-node@v3
          with:
            node_version: 16
        - name: install dependencies
          run: npm install
        - name: Trigger Post Merge workflow
          run: node jobs/triggerPostMergeWorkflow.js
          env:
            BRANCH_NAME: ${{ contexts.github.ref_name }}
            GITHUB_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}